id: P25B56487
initial_creation_type: input
source_metadata:
  title: Adzom Drukpa Series
  language: en
  description: 'Texts by and about Adzom Drukpa Drodül Pawo Dorje (a ''dzoms ''brug
    pa ''gro ''dul dpa'' bo rdo rje, 1842–1924):'
  volume:
    74c28938890744808f58f4eb5e378ee4:
      title: 'The Hook of Blessing and Compassion: An Invocation Recalling Briefly
        the Life and Liberation of the Drukchen Drodül Pawo Dorje, My Loving Supreme
        Guru'
      parent: Biography
    3d62bc32db6e4d8a9b99804db10ff83e:
      title: 'The Ambrosia of Blessings: A Prayer to the Vidyādhara of Unparalleled
        Kindness, Drodül Pawo Dorje'
      parent: Prayers
created_at: '2022-02-28T22:34:53.367763'
last_modified_at: '2022-02-28T22:34:53.367770'
